### ISSUE TITLE
Response error handling fails when service returns 404

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#224]
I experienced this error on the current master branch, while using `bundle exec rake console` to manually test a doc example for BigQuery.

```
irb(main):020:0> data = bigquery.query sql
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/errors.rb:41:in `from_response'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/project.rb:230:in `query'
	from (irb):20
	from /Users/quartzmo/code/google/codez/gcloud-ruby/rakelib/console.rake:27:in `block in <top (required)>'
```

Because this error occurs while trying to initialize an ApiError from a non-success response from BigQuery, I modified my local `bigquery/project.rb` to raise the response object, then recreated the error with the following output (auth details removed):

```
#<Google::APIClient::Result:0x007fe2e27127e0 @request=#<Google::APIClient::Request:0x007fe2e274b018 @parameters={"projectId"=>nil}, @headers={"Content-Type"=>"application/json", "User-Agent"=>"gcloud-ruby/0.2.0 google-api-ruby-client/0.8.6 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip"}, @api_method=#<Google::APIClient::Method:0x3ff170e6b954 ID:bigquery.jobs.query>, @authenticated=nil, @authorization=#<Google::Auth::UserRefreshCredentials:0x007fe2e1995e78 [HIDDEN]>, @body="{\"kind\":\"bigquery#queryRequest\",\"query\":\"SELECT TOP(word, 50) as word, COUNT(*) as count FROM publicdata:samples.shakespeare\"}">, @response=#<Faraday::Response:0x007fe2e27137a8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="Not Found" @url=#<URI::HTTPS https://www.googleapis.com/bigquery/v2/projects//queries> @request=#<Faraday::RequestOptions params_encoder=Faraday::FlatParamsEncoder> @request_headers={"User-Agent"=>"gcloud-ruby/0.2.0 google-api-ruby-client/0.8.6 Mac OS X/10.10.5\n (gzip)", "Content-Type"=>"application/json", "Accept-Encoding"=>"gzip", "Authorization"=>"[HIDDEN]", "Cache-Control"=>"no-store"} @ssl=#<Faraday::SSLOptions verify=true, ca_file="/Users/quartzmo/.rbenv/versions/2.2.2/gemsets/gcloud-ruby/gems/google-api-client-0.8.6/lib/cacerts.pem"> @response_headers={"cache-control"=>"no-cache, no-store, max-age=0, must-revalidate", "pragma"=>"no-cache", "expires"=>"Fri, 01 Jan 1990 00:00:00 GMT", "date"=>"Wed, 19 Aug 2015 01:02:49 GMT", "vary"=>"Origin, X-Origin", "content-type"=>"text/html; charset=UTF-8", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "server"=>"GSE", "alternate-protocol"=>"443:quic,p=1", "alt-svc"=>"quic=\":443\"; p=\"1\"; ma=604800", "connection"=>"close", "transfer-encoding"=>"chunked"} @status=404>>>
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/project.rb:230:in `query'
```

The relevant parts are: `@env=#<Faraday::Env @method=:post @body="Not Found" @url=#<URI::HTTPS https://www.googleapis.com/bigquery/v2/projects//queries>` and `@status=404`.

The `else` condition in [this block](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/bigquery/project.rb#L227-L231) should support all non-success responses.

**Comment by blowmage** [comment]
I've seen this when my environment isn't set up correctly and I don't have a `PROJECT_ID` configured. I suspect that is what is going on here. So there may be multiple changes to address this, one to guard against a missing project, and another to guard against API calls not returning the expected JSON payload.

**Comment by quartzmo** [comment]
Agreed. 
* #225 is to guard against a missing project
* This issue (#224) is to guard against API calls not returning the expected JSON payload

**Comment by quartzmo** [comment]
The commit above handles 404 response as shown in this example:
```
irb(main):005:0> data = bigquery.query sql
Gcloud::Bigquery::ApiError: Not Found: /bigquery/v2/projects//queries
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/project.rb:230:in `query'
	from (irb):5
```

**Comment by quartzmo** [comment]
I guess maybe it would be nice if the ApiError `message` contained "404" as well, just to be clear. Calling `ApiError#code` will return `404`. Should I prepend the code to the message?
