### ISSUE TITLE
Require pathname library in gcloud

### ISSUE THREAD

**Issue by vitaliel** [GoogleCloudPlatform/gcloud-ruby#265]
Snippet:
```ruby
require 'gcloud'
gcloud = Gcloud.new project_id, key_file

bigquery = gcloud.bigquery

dataset = bigquery.dataset 'logging'
table_name = 'logs_dev'
table = dataset.table table_name

load_job = table.load 'site_access.csv'

```
Exception
```
$ time ./bin/bq_uploader                                      
GEM_HOME/gcloud-0.3.0/lib/gcloud/bigquery/connection.rb:583:in 
`load_media': undefined method `Pathname' for #<Gcloud::Bigquery::Connection:0x9d94de8 (NoMethodError)
	from /home/ana/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/connection.rb:305:in `load_resumable'
	from /home/ana/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/table.rb:758:in `load_resumable'
	from /home/ana/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/table.rb:750:in `load_local'
	from /home/ana/.rvm/gems/ruby-2.2.2@bq_uploader/gems/gcloud-0.3.0/lib/gcloud/bigquery/table.rb:613:in `load'
	from /home/lz/projects/cc/bq_uploader/lib/cc/bq_uploader.rb:40:in `initialize'
	from ./bin/bq_uploader:10:in `new'
	from ./bin/bq_uploader:10:in `<main>'
```

If I add require 'pathname' before requiring gcloud it works.

**Comment by blowmage** [comment]
Thank you for opening this issue.
