### ISSUE TITLE
Zlib::GzipFile::Error: not in gzip format

### ISSUE THREAD

**Issue by gramos74** [GoogleCloudPlatform/gcloud-ruby#367]
I'm trying to load a file in a google bigquery table, but when I execute:

```ruby
bigquery = gcloud.bigquery
```

A receive a: `Zlib::GzipFile::Error: not in gzip format`

That it's only fixed if I set:

```ruby
Faraday.default_adapter = :net_http
```

Which it's weird because everywhere is recommended to use `:httpclient` as adapter, and it is what I'm using.

BTW, If I set the adapter to `:net_http` then all works except the upload that generates the error: 

```
Errno::EPIPE: Broken pipe
```

I'm lost... any help ?

**Comment by jgeewax** [comment]
Thanks for reporting @gramos74 -- definitely seems like a weird error. Is that the full stack trace for the exception? I have a feeling that line numbers and whatnot will be helpful in debugging this one.

**Comment by quartzmo** [comment]
@gramos74 Sorry to hear that you ran into this problem. You're right that [our current recommendation](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/266#issuecomment-137510311) to avoid `Broken pipe` errors with large uploads is to use httpclient.

```
Faraday.default_adapter = :httpclient
```

We will investigate this new issue with gzip today, thank you. As @jgeewax says, if you have additional details that may help us, please post add them here.

**Comment by gramos74** [comment]
Hi

This is the current Gemfile.lock:

    gcloud (0.3.1)
      beefcake (~> 1.0)
      digest-crc (~> 0.4)
      google-api-client (~> 0.8.3)
      mime-types (~> 2.4)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    google-api-client (0.8.3)
      activesupport (>= 3.2)
      addressable (~> 2.3)
      autoparse (~> 0.3)
      extlib (~> 0.9)
      faraday (~> 0.9)
      googleauth (~> 0.3)
      launchy (~> 2.4)
      multi_json (~> 1.10)
      retriable (~> 1.4)
      signet (~> 0.6)
    googleauth (0.4.0)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 1.8)
      memoist (~> 0.11)
      multi_json (= 1.11)
      signet (~> 0.6)
    launchy (2.4.3)
      addressable (~> 2.3)
    extlib (0.9.16)
    autoparse (0.3.3)
      addressable (>= 2.3.1)
      extlib (>= 0.9.15)
      multi_json (>= 1.0.0)
    beefcake (1.1.0)
    digest-crc (0.4.1)
    multipart-post (2.0.0)
    signet (0.6.0)
      addressable (~> 2.3)
      extlib (~> 0.9)
      faraday (~> 0.9)
      jwt (~> 1.0)
      multi_json (~> 1.10)
    retriable (1.4.1)     
    httpclient (2.6.0.1)

( I tried to put only the things related to gcloud... our gemfile is huge )

And this is the code that I'm using:

require 'gcloud'

module GoogleApi
  module BigQuery
    class Adapter

      def initialize(configuration)

        gcloud = Gcloud.new(configuration.application.project_id, "#{Rails.root}/config/gbq-key.json")

        @bigquery = gcloud.bigquery

      end

      def create_table(dataset_name, table_name, file_path = nil)

        file   = File.open file_path
        schema = YAML.load_file(Rails.root + 'app' + 'services' + 'gbq' +'schema.yml')

        dataset = @bigquery.dataset dataset_name
        dataset = @bigquery.create_dataset dataset_name if dataset.nil?

        table   = dataset.table(table_name)
        table   = dataset.create_table(table_name, :schema => schema) if table.nil?

        table.load file, chunk_size: 1 * 1024 * 1024
      end

    end
  end
end

**Comment by quartzmo** [comment]
@gramos74 Thank you. Do you have a backtrace for the error that you can also add here?

**Comment by gramos74** [comment]
For the first error ( getting the bigquery object ):

```
Google::APIClient - Initializing client with options {:application_name=>"gcloud-ruby", :application_version=>"0.3.1"}
Google::APIClient::Request Sending API request get https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>""}
Decompressing gzip encoded response (85789 bytes)
Zlib::GzipFile::Error: not in gzip format
from /Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client/gzip.rb:14:in `initialize'
```

And for the second one ( loading the file and changing the faraday adapter to net_http)

```
Google::APIClient::Request Sending API request get https://www.googleapis.com/bigquery/v2/projects/zzzzzzzzzz/datasets/admin {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>"", "Authorization"=>"Bearer xxxxxxxxxxxxxx", "Cache-Control"=>"no-store"}
Decompressing gzip encoded response (405 bytes)
Decompressed (715 bytes)
Google::APIClient::Request Result: 200 {"expires"=>"Wed, 07 Oct 2015 16:36:07 GMT", "date"=>"Wed, 07 Oct 2015 16:36:07 GMT", "cache-control"=>"private, max-age=0, must-revalidate, no-transform", "etag"=>"\"hnk59tKBkX8cdlePZ8VtzgVzuO4/MTQ0NDE2NjAzNjE2OA\"", "vary"=>"Origin, X-Origin", "content-type"=>"application/json; charset=UTF-8", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "server"=>"GSE", "alternate-protocol"=>"443:quic,p=1", "alt-svc"=>"quic=\":443\"; p=\"1\"; ma=604800", "connection"=>"close", "transfer-encoding"=>"chunked"}
Google::APIClient::Request Sending API request get https://www.googleapis.com/bigquery/v2/projects/zzzzzzzzz/datasets/admin/tables/test_gabi {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>"", "Authorization"=>"Bearer xxxxxxxxxxxx", "Cache-Control"=>"no-store"}
Decompressing gzip encoded response (930 bytes)
Decompressed (6121 bytes)
Google::APIClient::Request Result: 200 {"expires"=>"Wed, 07 Oct 2015 16:36:08 GMT", "date"=>"Wed, 07 Oct 2015 16:36:08 GMT", "cache-control"=>"private, max-age=0, must-revalidate, no-transform", "etag"=>"\"hnk59tKBkX8cdlePZ8VtzgVzuO4/MTQ0NDIxNTkyMjE5NA\"", "vary"=>"Origin, X-Origin", "content-type"=>"application/json; charset=UTF-8", "x-content-type-options"=>"nosniff", "x-frame-options"=>"SAMEORIGIN", "x-xss-protection"=>"1; mode=block", "server"=>"GSE", "alternate-protocol"=>"443:quic,p=1", "alt-svc"=>"quic=\":443\"; p=\"1\"; ma=604800", "connection"=>"close", "transfer-encoding"=>"chunked"}
Google::APIClient::Request Sending API request post https://www.googleapis.com/upload/bigquery/v2/projects/zzzzzzzzzzzzz/jobs?uploadType=resumable {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "X-Upload-Content-Type"=>"application/octet-stream", "X-Upload-Content-Length"=>"15329557", "Content-Type"=>"application/json", "Accept-Encoding"=>"gzip", "Authorization"=>"Bearer xxxxxxxxxxxxxxxxxx", "Cache-Control"=>"no-store"}
Google::APIClient::Request Result: 200 {"x-guploader-uploadid"=>"AEnB2Up1OrRjme7cQPQsfwvcMixkGRqo991WxYj4X-zmlJ8kukGAyEc6jpopAO0qGMlibBl7OA5LTfcyV0UcSpb4Up2vksFTTw", "location"=>"https://www.googleapis.com/upload/bigquery/v2/projects/zzzzzzzzzzzz/jobs?uploadType=resumable&upload_id=AEnB2Up1OrRjme7cQPQsfwvcMixkGRqo991WxYj4X-zmlJ8kukGAyEc6jpopAO0qGMlibBl7OA5LTfcyV0UcSpb4Up2vksFTTw", "etag"=>"\"hnk59tKBkX8cdlePZ8VtzgVzuO4/z4n5QqOfTFnD7LJcE_7xj45hFNs\"", "vary"=>"Origin, X-Origin", "cache-control"=>"no-cache, no-store, max-age=0, must-revalidate", "pragma"=>"no-cache", "expires"=>"Fri, 01 Jan 1990 00:00:00 GMT", "date"=>"Wed, 07 Oct 2015 16:36:09 GMT", "content-length"=>"0", "server"=>"UploadServer", "content-type"=>"text/html; charset=UTF-8", "alternate-protocol"=>"443:quic,p=1", "alt-svc"=>"quic=\":443\"; p=\"1\"; ma=604800", "connection"=>"close"}
Google::APIClient::Request Sending upload body
Google::APIClient::ResumableUpload Sending API request post https://www.googleapis.com/upload/bigquery/v2/projects/zzzzzzzz/jobs?uploadType=resumable&upload_id=AEnB2Up1OrRjme7cQPQsfwvcMixkGRqo991WxYj4X-zmlJ8kukGAyEc6jpopAO0qGMlibBl7OA5LTfcyV0UcSpb4Up2vksFTTw {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "X-Upload-Content-Type"=>"application/octet-stream", "X-Upload-Content-Length"=>"15329557", "Content-Type"=>"application/octet-stream", "Accept-Encoding"=>"gzip", "Content-Length"=>"1048576", "Content-Range"=>"bytes 0-1048575/15329557", "Authorization"=>"Bearer xxxxxxxxxxxxxxxxxxxxxx", "Cache-Control"=>"no-store"}
Errno::EPIPE: Broken pipe
from /Users/gabi/.rbenv/versions/2.1.1/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite'

```

**Comment by quartzmo** [comment]
Do you have the full backtrace for the first error? That might help.

**Comment by gramos74** [comment]
Yes... sorry

```
Google::APIClient - Initializing client with options {:application_name=>"gcloud-ruby", :application_version=>"0.3.1"}
Google::APIClient::Request Sending API request get https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.3 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>""}
Decompressing gzip encoded response (85789 bytes)
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client/gzip.rb:14:in `initialize'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client/gzip.rb:14:in `new'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client/gzip.rb:14:in `on_complete'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client/request.rb:163:in `send'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb:645:in `block in execute!'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb:636:in `execute!'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb:368:in `discovery_document'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/google-api-client-0.8.3/lib/google/api_client.rb:413:in `discovered_api'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud/bigquery/connection.rb:40:in `initialize'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud/bigquery/project.rb:57:in `new'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud/bigquery/project.rb:57:in `initialize'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud/bigquery.rb:64:in `new'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud/bigquery.rb:64:in `bigquery'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/gcloud-0.3.1/lib/gcloud.rb:254:in `bigquery'
/Users/gabi/Development/version4/lib/google_api/big_query/adapter.rb:13:in `initialize'
(pry):1:in `new'
(pry):1:in `<main>'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `call'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/pry-byebug-3.0.1/lib/pry-byebug/pry_ext.rb:16:in `start_with_pry_byebug'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
/Users/gabi/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by quartzmo** [comment]
Great, thank you.

**Comment by quartzmo** [comment]
So far, I am not able to reproduce this error.

**Comment by quartzmo** [comment]
This is the output I'm seeing, with Google API Client debug logging:

```
irb(main):017:0> @bigquery = @client.discovered_api "bigquery", API_VERSION
D, [2015-10-07T11:00:11.016632 #9485] DEBUG -- : Google::APIClient::Request Sending API request get https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest {"User-Agent"=>"gcloud-ruby/0.3.1 google-api-ruby-client/0.8.6 Mac OS X/10.10.5\n (gzip)", "Accept-Encoding"=>"gzip", "Content-Type"=>""}
D, [2015-10-07T11:00:11.278870 #9485] DEBUG -- : Decompressing gzip encoded response (12672 bytes)
D, [2015-10-07T11:00:11.280678 #9485] DEBUG -- : Decompressed (85789 bytes)
D, [2015-10-07T11:00:11.284591 #9485] DEBUG -- : Google::APIClient::Request Result: 200 {"Expires"=>"Wed, 07 Oct 2015 17:05:08 GMT", "Date"=>"Wed, 07 Oct 2015 17:00:08 GMT", "Cache-Control"=>"public, max-age=300, must-revalidate, no-transform", "ETag"=>"\"ye6orv2F-1npMW3u9suM3a7C5Bo/WAvGgZIa_w_D-chJ6XIN_nETC5g\"", "Vary"=>"X-Origin", "Content-Type"=>"application/json; charset=UTF-8", "X-Content-Type-Options"=>"nosniff", "X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "Content-Length"=>"13177", "Server"=>"GSE", "Alternate-Protocol"=>"443:quic,p=1", "Alt-Svc"=>"quic=\":443\"; p=\"1\"; ma=604800"}
=> #<Google::APIClient::API:0x3ff5d53a5f10 ID:bigquery:v2>
```

**Comment by quartzmo** [comment]
This is very interesting, the decompressed byte count in my output:

```
D, [2015-10-07T11:00:11.278870 #9485] DEBUG -- : Decompressing gzip encoded response (12672 bytes)
D, [2015-10-07T11:00:11.280678 #9485] DEBUG -- : Decompressed (85789 bytes)
```

is the same as the `gzip encoded response` byte count in yours:

```
Decompressing gzip encoded response (85789 bytes)
```

It appears that the response you are receiving is perhaps indeed not in gzip format, as indicated by the error, but has already been decompressed.

**Comment by gramos74** [comment]
I changed the adapter to net_http due to: https://github.com/google/google-api-ruby-client/issues/121

seems that the response arrives compressed but it is automatically decompressed before to be passed back to the google-api-client

**Comment by blowmage** [comment]
At first I didn't get a gzipped response when curling the discovery URL:

```
$ curl https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest -v -H "Accept-Encoding: gzip"
*   Trying 216.58.217.42...
* Connected to www.googleapis.com (216.58.217.42) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.googleapis.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
> GET /discovery/v1/apis/bigquery/v2/rest HTTP/1.1
> Host: www.googleapis.com
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 200 OK
< Expires: Wed, 07 Oct 2015 17:11:06 GMT
< Date: Wed, 07 Oct 2015 17:06:06 GMT
< ETag: "ye6orv2F-1npMW3u9suM3a7C5Bo/P_gjIj9cxEFBgf-j3vh--gQOYRM"
< Vary: Origin
< Vary: X-Origin
< Content-Type: application/json; charset=UTF-8
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Content-Length: 85789
< Server: GSE
< Cache-Control: public, max-age=300, must-revalidate, no-transform
< Age: 132
< Alternate-Protocol: 443:quic,p=1
< Alt-Svc: quic=":443"; p="1"; ma=604800
< 
{...}
```

But afterwards I did:

```
$ curl https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest -v -H "Accept-Encoding: gzip"
*   Trying 216.58.217.42...
* Connected to www.googleapis.com (216.58.217.42) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.googleapis.com
* Server certificate: Google Internet Authority G2
* Server certificate: GeoTrust Global CA
> GET /discovery/v1/apis/bigquery/v2/rest HTTP/1.1
> Host: www.googleapis.com
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 200 OK
< Expires: Wed, 07 Oct 2015 17:17:15 GMT
< Date: Wed, 07 Oct 2015 17:12:15 GMT
< ETag: "ye6orv2F-1npMW3u9suM3a7C5Bo/WAvGgZIa_w_D-chJ6XIN_nETC5g"
< Vary: Origin
< Vary: X-Origin
< Content-Type: application/json; charset=UTF-8
< Content-Encoding: gzip
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Content-Length: 13177
< Server: GSE
< Cache-Control: public, max-age=300, must-revalidate, no-transform
< Age: 32
< Alternate-Protocol: 443:quic,p=1
< Alt-Svc: quic=":443"; p="1"; ma=604800
< 
?}is?F??w? ...
```

Notice how the `Content-Encoding: gzip` header wasn't returned in the first response, but was included in the second. This makes me thing something is going on with the discovery service where it doesn't gzip reliably, combined with an HTTPClient bug where it doesn't check the encoding of the response.

**Comment by quartzmo** [comment]
I am looking into the possibility that httpclient does some automatic/transparent decompression that google api client isn't anticipating.

**Comment by gramos74** [comment]
I found something... by default when I instal the gem, the faraday version 0.9.2 is installed.
But if I force the faraday version 0.9.1 it works fine

**Comment by gramos74** [comment]
and even the load of the file works fine... so there is some changes in the faraday gem from version 0.9.1 to 0.9.2 that makes the service discovery fail.

**Comment by blowmage** [comment]
Yeah, that's the key. The first item on the [Faraday 0.9.2 release notes](https://github.com/lostisland/faraday/releases/tag/v0.9.2) states:

> Enable gzip compression for httpclient

This is obviously conflicting with the [gzip middleware](https://github.com/google/google-api-ruby-client/blob/v0.8.3/lib/google/api_client/gzip.rb) that Google API Client adds.

Good job everyone! I think we have enough to reproduce and open an issue on Google API Client.

**Comment by gramos74** [comment]
Thanks Guys for your help! :)

**Comment by blowmage** [comment]
Here are the [changes from the 0.9.1 and 0.9.2 releases](https://github.com/lostisland/faraday/compare/v0.9.1...v0.9.2).

**Comment by quartzmo** [comment]
As you can see in [the 0.9.2 Faraday adapter for httpclient](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/httpclient.rb#L14), there does not appear to be any way to override the new configuration.

**Comment by blowmage** [comment]
Unfortunately I think the guidance should be to pin a dependency on faraday 0.9.1 until a new version of google-api-client can be released that will resolve this.

**Comment by quartzmo** [comment]
I found a workaround for this issue:

Note that this workaround is only needed when using gcloud with [httpclient](https://github.com/nahi/httpclient) (or another http library that does gzip decompression when used with Faraday).

To rely only on Faraday 0.9.2's enabling of `httpclient` decompression, and prevent the later attempt by [google-api-ruby-client Faraday middleware](https://github.com/google/google-api-ruby-client/blob/v0.8.3/lib/google/api_client/gzip.rb) to decompress the response, replace the Gzip middleware with the simple, do-nothing superclass.
```
require 'faraday'
Faraday.default_adapter = :httpclient

# override gzip middleware with no-op
Faraday::Response.register_middleware :gzip => Faraday::Response::Middleware
```

/cc @gramos74 @jgeewax

**Comment by blowmage** [comment]
Great job @quartzmo!

**Comment by gramos74** [comment]
Cool @quartzmo !

**Comment by quartzmo** [comment]
Thanks guys! I'm working on a PR to update the documentation in places where it recommends using httpclient.

**Comment by EssentialMusic** [comment]
Thanks @quartzmo , lifesaver!

**Comment by dolzenko** [comment]
The 0.9.2 Faraday fix didn't work for me, pinning to 0.9.1 did.

**Comment by quartzmo** [comment]
@dolzenko I'm surprised that [this workaround for Faraday 0.9.2](https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/367#issuecomment-146301677) didn't work for you, but if you can pin to 0.9.1, yes, that should avoid the issue entirely.

**Comment by dolzenko** [comment]
@quartzmo thanks for your help, btw why gem isn't shipped with all this configuration applied? httpclient, faraday version - its been a tough ride for me - first gzip errors, then broken pipes...

**Comment by blowmage** [comment]
I'm disappointed the 0.8.x line of Google API Client was never updated to fix this bug. We are working towards migrating to the 0.9.x version of Google API Client which switched away from Faraday to Hurley, and should solve this issue as well as some others.

Downgrading to Faraday 0.9.1 is likely the safest approach if you plan on using the HTTPClient middleware.

**Comment by quartzmo** [comment]
@dolzenko As @blowmage explains, we are hoping that the overall situation will improve soon.

Regarding applying the configuration documented here and in our API docs, I think we have been correctly hesitant to risk introducing yet more problems with configuration in our layer. In my opinion, it is well-intentioned "baked-in" configuration (such as "Enable gzip compression for httpclient" in 0.9.2) that causes unforeseen problems such as this one.

**Comment by ThadeuBrito** [comment]
In case to use VCR? I have this same error, I can  rec the VCR but I can't read it.

```
     Failure/Error: Unable to find matching line from backtrace
     Zlib::GzipFile::Error:
       not in gzip format
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `initialize'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `new'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client/gzip.rb:14:in `on_complete'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:163:in `send'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:in `execute!'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client.rb:368:in `discovery_document'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/google-api-client-0.8.6/lib/google/api_client.rb:413:in `discovered_api'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud/bigquery/connection.rb:41:in `initialize'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud/bigquery/project.rb:59:in `new'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud/bigquery/project.rb:59:in `initialize'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud/bigquery.rb:56:in `new'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud/bigquery.rb:56:in `bigquery'
     # /Users/thadeubrito/.rvm/gems/ruby-2.1.5/gems/gcloud-0.11.0/lib/gcloud.rb:225:in `bigquery'
     # ./config/bigquery_connection.rb:6:in `create_bigquery_connection'
     # ./spec/support/authentication_bigquery.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by blowmage** [comment]
What version of Faraday? Do you have any of the workarounds in place?

**Comment by ThadeuBrito** [comment]
Faraday version is `0.9.2` but I have already pin to `0.9.1` and it did not work.
The curious fact is:
1 - I recorded the VCR using the gcloud gem
2 - I switch to use the `abronte/BigQuery` gem, and the `abronte/BigQuery` gem can read the VCR recorded by gcloud

It is not a great flow to work : )

**Comment by quartzmo** [comment]
@ThadeuBrito We are planning to complete work for #269 (Upgrade to Google API Client 0.9) very soon. Will you be able to upgrade gcloud-ruby after we release this to see if it resolves your issue?

**Comment by ThadeuBrito** [comment]
Of course, it is gonna be awesome!!

**Comment by quartzmo** [comment]
@ThadeuBrito Great. We are working on the upgrade right now.

**Comment by ThadeuBrito** [comment]
My query was returning a large data, more than 20588 lines. I was not running the `.next` to get the rest of data, so in my option the saved gzip on VCR was broken, so it could not unzio that. 

I was using it:
```ruby
  def query(sql)
    sql_string = parse_sql(sql)
    data = $bigquery_client.query(sql_string)
  end
```
I did not sure how I fixed that, but i'm just using it:
```ruby
  def query(sql)
    sql_string = parse_sql(sql)
    data = $bigquery_client.query(sql_string)
    new_data = data
    while data.next?
      next_page = data.next
      new_data += next_page
      data = next_page
    end
    return new_data
  end
```

Thanks for all : )

**Comment by blowmage** [comment]
You can tighten that up if you are using the latest release. You can use the `all` enumerator to get all the rows on all the pages, and call `to_a` on it to get it as an array:

```ruby
  def query(sql)
    sql_string = parse_sql(sql)
    data = $bigquery_client.query(sql_string)
    data.all.to_a
  end
```

**Comment by ThadeuBrito** [comment]
awesome @blowmage . Thanks!
