### ISSUE TITLE
Gcloud::Storage::Bucket#create_file cause NoMemoryError

### ISSUE THREAD

**Issue by miyukki** [GoogleCloudPlatform/gcloud-ruby#426]
When I was uploading a file is about 1GB over, it cause NoMemoryError fail.

The stack trace is below:
```
NoMemoryError: failed to allocate memory
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client/media.rb:78:in `read'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client/media.rb:78:in `read'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/adapter/httpclient.rb:34:in `call'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client/request.rb:163:in `send'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client/request.rb:174:in `send'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client.rb:645:in `block in execute!'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client.rb:636:in `execute!'
  from /<my_project_dir>/bundle/ruby/2.2.0/bundler/gems/google-api-ruby-client-a194240a9da8/lib/google/api_client.rb:679:in `execute'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/gcloud-0.5.0/lib/gcloud/storage/connection.rb:370:in `insert_file'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/gcloud-0.5.0/lib/gcloud/storage/connection.rb:193:in `upload_file'
  from /<my_project_dir>/bundle/ruby/2.2.0/gems/gcloud-0.5.0/lib/gcloud/storage/bucket.rb:602:in `create_file'
```

The solution solve this problem is must set `chunk_size` option to `create_file`.

1. https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/lib/gcloud/storage/connection.rb#L379-L380
`Gcloud::Storage::Connection#file_media` set the  `chunk_size` if only `resumable` and already set `chunk_size` is above 256KB option to `create_file`.

2. https://github.com/google/google-api-ruby-client/blob/v0.8.6/lib/google/api_client/media.rb#L203
`Google::APIClient::ResumableUpload#to_http_request` set the `chunk_size` from `media.chunk_size`.
But `chunk_size` set to `media.length` if `media.chunk_size` is `nil`.

----

Would you write to "A note about large uploads" section of gcloud-docs this solution for someone is faced this problem?

http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.5.0/Gcloud/Storage.html#module-Gcloud::Storage-label-A+note+about+large+uploads

**Comment by quartzmo** [comment]
@miyukki, yes we will. Thank you very much for both finding the problem and providing the solution!

**Comment by quartzmo** [comment]
@miyukki Does PR #431 resolve this issue for you?

**Comment by miyukki** [comment]
Sounds good :smiley:

**Comment by blowmage** [comment]
Thanks!
