### ISSUE TITLE
MultiJson::ParseError while using faraday 0.9.1

### ISSUE THREAD

**Issue by doooby** [GoogleCloudPlatform/gcloud-ruby#449]
Hi,
I just run into a problem and since realizing what was the issue took me quite some time, I thought you should be noticed. (and anybody who'd get himself in the same situation).

After merging a feature into our master branch, simple connection to google cloud services started to throw:

```ruby
    require 'gcloud'
    require 'httpclient'
    Faraday.default_adapter = :httpclient
    require 'google/api_client'
    Faraday::Response.register_middleware gzip: Faraday::Response::Middleware
    client = ::Gcloud.new 'project-id', Rails.root.join('config', 'gcloud.json')
    client.bigquery.dataset('test')

    => MultiJson::ParseError: 795: unexpected token at '�'
	from /json-1.8.3/lib/json/common.rb:155:in `parse'
	from /json-1.8.3/lib/json/common.rb:155:in `parse'
	from /multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:14:in `load'
	from /multi_json-1.11.2/lib/multi_json/adapter.rb:21:in `load'
	from /multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	from /google-api-client-0.8.6/lib/google/api_client/result.rb:144:in `data'
```

As mush as I've dug into, there's some problem during connection, some response has a body, that has invalid encoding. And therefore that json parsing error.

Anyway, after some time, I realized that only difference between my develop version and master after merge was that for dev gemlock stated "faraday 0.9.2" and in master it was "faraday 0.9.1". I do not know what was the cause, but using faraday 0.9.2 made that error disappear.

**Comment by blowmage** [comment]
Thanks for letting us know. We will investigate and let you know what we find.

**Comment by quartzmo** [comment]
Unfortunately, I could not reproduce this, although I used the same gem versions shown in your backtrace:

```sh
$ bundle show
Gems included by the bundle:
  * activesupport (4.2.5)
  * addressable (2.3.8)
  * ast (2.1.0)
  * astrolabe (1.3.1)
  * autoparse (0.3.3)
  * autotest-suffix (1.1.0)
  * beefcake (1.1.0)
  * builder (3.2.2)
  * bundler (1.10.6)
  * coveralls (0.8.9)
  * digest-crc (0.4.1)
  * doc2json (1.0.0.pre.alpha.1)
  * docile (1.1.5)
  * domain_name (0.5.25)
  * extlib (0.9.16)
  * faraday (0.9.1)
  * gcloud (0.5.0)
  * gcloud-rdoc (1.0.0 b879b18)
  * google-api-client (0.8.6)
  * googleauth (0.4.2)
  * http-cookie (1.0.2)
  * httpclient (2.7.0.1)
  * i18n (0.7.0)
  * json (1.8.3)
  * jwt (1.5.2)
  * launchy (2.4.3)
  * little-plugger (1.1.4)
  * logging (2.0.0)
  * memoist (0.13.0)
  * mime-types (2.99)
  * minitest (5.8.3)
  * minitest-autotest (1.0.1)
  * minitest-focus (1.1.2)
  * minitest-rg (5.2.0)
  * minitest-server (1.0.3)
  * multi_json (1.11.2)
  * multipart-post (2.0.0)
  * netrc (0.11.0)
  * parser (2.2.3.0)
  * powerpack (0.1.1)
  * rainbow (2.0.0)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * rest-client (1.8.0)
  * retriable (1.4.1)
  * rubocop (0.35.1)
  * ruby-progressbar (1.7.5)
  * signet (0.6.1)
  * simplecov (0.10.0)
  * simplecov-html (0.10.0)
  * term-ansicolor (1.3.2)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tins (1.6.0)
  * tzinfo (1.2.2)
  * unf (0.1.4)
  * unf_ext (0.0.7.1)
  * yard (0.8.7.6)
  * yard-xml (0.1.3)
  * zonefile (1.04)
$ bundle exec rake console
irb(main):001:0> bigquery = gcloud.bigquery
=> #<Gcloud::Bigquery::Project:0x007faabc595c18 @connection=Gcloud::Bigquery::Connection(xyz)>
irb(main):002:0> dataset = bigquery.dataset "test_1"
=> #<Gcloud::Bigquery::Dataset:0x007faabd4a6928 ... >
```

**Comment by doooby** [comment]
Getting back to it, it sure is only this issue: #367 . I have had little time to inspect it carefully.
from my example comment out that

```
    Faraday::Response.register_middleware gzip: Faraday::Response::Middleware
```

and no problem with faraday 0.9.1.
That line is neccessary with faraday 0.9.2 though.

Since the documentation states that clear, I appologies for posting that..

**Comment by quartzmo** [comment]
Thanks @doooby, we always appreciate help finding issues and totally understand that finding the cause can be hard. Never hesitate to open an issue when something isn't working.
