### ISSUE TITLE
Filter should not be optional in Project#create_metric

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#574]
Although the official docs for [LogMetric](https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/projects.metrics#LogMetric) do not specify `filter` as required, based on both the way Metrics work, and the behavior of the service, it is:

```sh
irb(main):038:0> metric = logging.create_metric "mymetric", filter: "severity:ERROR"
=> #<Gcloud::Logging::Metric:0x007fb9caaf6618 @service=Gcloud::Logging::Service(nodal-almanac-725), @grpc=<Google::Logging::V2::LogMetric: name: "mymetric", description: "", filter: "severity:ERROR">>
irb(main):039:0> metric = logging.create_metric "mymetric2", filter: nil
Gcloud::InvalidArgumentError: 3:Request contains an invalid argument.
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/logging/project.rb:544:in `rescue in create_metric'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/logging/project.rb:540:in `create_metric'
	from (irb):39
```

**Comment by blowmage** [comment]
Agreed. Found this when working on the acceptance tests.
