### ISSUE TITLE
rescue in acknowledge: 3:You have not specified an ack ID in the request. (Gcloud::InvalidArgumentError)

### ISSUE THREAD

**Issue by maxstudener** [GoogleCloudPlatform/gcloud-ruby#606]
This is happening in version 0.7.0
Code randomly trys to acknowledge message with in listen loop, but didn't actually receive a message.

Code to publish to topic
```ruby
require "gcloud"

gcloud = Gcloud.new
pubsub = gcloud.pubsub

topic = pubsub.topic "topic-name"

msgs = topic.publish do |batch|
  batch.publish "new-message-1", foo: :bar
  batch.publish "new-message-2", foo: :baz
  batch.publish "new-message-3", foo: :bif
  batch.publish "new-message-4", foo: :bif
  batch.publish "new-message-5", foo: :bif
  batch.publish "new-message-6", foo: :bif
  batch.publish "new-message-7", foo: :bif
  batch.publish "new-message-8", foo: :bif
end
```

Code to listen, this happens when you have two listeners running at the same time to the same subscription.
```ruby
require "gcloud"
gcloud = Gcloud.new
sub = pubsub.subscription "topic-name-sub"

sub.listen  max: 2, autoack: true do |msg|
  puts "#{Time.now.to_f * 1000} - #{Base64.decode64(msg.data)}"
end
```

Stack trace
```ruby
/Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:363:in `rescue in acknowledge': 3:You have not specified an ack ID in the request. (Gcloud::InvalidArgumentError)
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:358:in `acknowledge'
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:241:in `pull'
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:274:in `wait_for_messages'
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:327:in `block in listen'
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:326:in `loop'
	from /Users/mstuden/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/gcloud-0.7.0/lib/gcloud/pubsub/subscription.rb:326:in `listen'
	from listen.rb:5:in `<main>'
```

**Comment by quartzmo** [comment]
@maxstudener Thank you for reporting this. I really appreciate your detailed issue! We will look into it today.

**Comment by maxstudener** [comment]
Just tried running with only one listener and it has the same issue. Going to try a different ruby version to see if it makes a difference.

**Comment by maxstudener** [comment]
i will add that after it acknowledges the message, you have to wait about a minute and then the error occurs

**Comment by maxstudener** [comment]
appears to happen in 2.2.2p95 and 2.0.0p648
