### ISSUE TITLE
Does any processing need to publish multibyte charactor to Pubsub?

### ISSUE THREAD

**Issue by mia-0032** [GoogleCloudPlatform/gcloud-ruby#709]
I am trying to send logs including multibyte charactor to Pubsub.
But encoding error is occured.
Does any processing such as Base64 encoding need to publish multibyte charactor to Pubsub?

My test environment is below:
Ubuntu 14.04
Ruby 2.3.1
gcloud-ruby 0.10.0

Test program is below:

```ruby
require "gcloud"

gcloud = Gcloud.new
pubsub = gcloud.pubsub

topic = pubsub.topic "my-topic", autocreate: true

msg = topic.publish "あ"
```

The error is below:
```
/home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/service.rb:125:in `encode': U+3042 from UTF-8 to ASCII-8BIT (Encoding::UndefinedConversionError)
	from /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/service.rb:125:in `block in publish'
	from /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/service.rb:123:in `map'
	from /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/service.rb:123:in `publish'
	from /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/topic.rb:499:in `publish_batch_messages'
	from /home/ubuntu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gcloud-0.10.0/lib/gcloud/pubsub/topic.rb:298:in `publish'
	from test.rb:8:in `<main>'
```

**Comment by quartzmo** [comment]
I can also reproduce this error:

```sh
irb(main):007:0> msg = topic.publish "\u3042"
Encoding::UndefinedConversionError: U+3042 from UTF-8 to ASCII-8BIT
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/service.rb:125:in `encode'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/service.rb:125:in `block in publish'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/service.rb:123:in `map'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/service.rb:123:in `publish'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/topic.rb:499:in `publish_batch_messages'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/pubsub/topic.rb:298:in `publish'
	from (irb):7

```

**Comment by blowmage** [comment]
Hi @mia-0032, thanks for opening this issue. This is definitely a bug. Publishing a string should not raise an error. We will get a fix applied and documentation updated ASAP.

For now, you can force the encoding of your string when publishing to avoid the error:

```ruby
require "gcloud"

gcloud = Gcloud.new
pubsub = gcloud.pubsub

topic = pubsub.topic "my-topic", autocreate: true

msg = topic.publish "あ".force_encoding("ASCII-8BIT")
```

Please note that the data returned by Pub/Sub will always be encoded as ASCII-8BIT. You can force those bytes back into UTF-8 using `val.force_encoding("UTF-8")`.

We have an open issue #453 for dealing with encoding and Pub/Sub messages. We would love to have your input on it as well.

**Comment by mia-0032** [comment]
Hi @blowmage, thank you for your reply.
I added `force_encoding` to my log collector plugin and succeeded to publish logs including multibyte charactor ! :)
I'll check #453 later.
