### ISSUE TITLE
downloading large file: failed to allocate memory (NoMemoryError)

### ISSUE THREAD

**Issue by Aguasvivas22** [GoogleCloudPlatform/gcloud-ruby#718]
Simple script to download file:
```
require 'gcloud'

gcloud = Gcloud.new "my-bucket"
storage = gcloud.storage

bucket = storage.bucket "my-bucket"
file = bucket.file "myfile.zip"
file.download "/tmp/myfile.zip"
```

When downloading 1.8GB file:

```
/opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file/**verifier.rb:55:in `read': failed to allocate memory (NoMemoryError)**
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file/verifier.rb:55:in `block in md5_for'
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file/verifier.rb:54:in `open'
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file/verifier.rb:54:in `md5_for'
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file/verifier.rb:31:in `verify_md5!'
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file.rb:688:in `verify_file!'
	from /opt/lang/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/gcloud-0.10.0/lib/gcloud/storage/file.rb:353:in `download'
	from pull.rb:11:in `<main>'
```

If I change 'verify' to 'none', I don't encounter this error.

free mem + cached > 3GB

**Comment by quartzmo** [comment]
@Aguasvivas22 Thanks for opening this issue! I'll see if I can reproduce it myself today.

**Comment by quartzmo** [comment]
I'm hoping that the solution will be to change the implementation to something that uses less memory (see "Compute digest by chunks" in examples for [Digest](http://ruby-doc.org/stdlib-2.2.3/libdoc/digest/rdoc/Digest.html)), but this is just an initial guess.

**Comment by Aguasvivas22** [comment]
Thanks!

Also, I should mention that even when with the "no memory error", it still seems to download the file successfully, so it's just the verification part that fails(?)

**Comment by Aguasvivas22** [comment]
Awesome.

Thanks, @quartzmo!

**Comment by quartzmo** [comment]
@Aguasvivas22 This fix was contributed by @blowmage!

**Comment by Aguasvivas22** [comment]
well then, thank you too @blowmage!
