### ISSUE TITLE
Support custom encryption keys for storage?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#722]
Can we support custom encryption keys for files uploaded?

Spec is here: https://cloud.google.com/compute/docs/disks/customer-supplied-encryption#top_of_page

**Comment by quartzmo** [comment]
Docs above are for Compute Engine, I believe this is the correct docs page for Storage:

https://cloud.google.com/storage/docs/encryption

**Comment by blowmage** [comment]
Been looking at this. This looks really cool.

**Comment by quartzmo** [comment]
This appears to work just fine. I added the headers as follows to `Bucket#create_file`:

```ruby
        headers = {
          "x-goog-encryption-algorithm" => "AES256",
          "x-goog-encryption-key" => Base64.encode64(options[:key]),   # TODO: delete entry for this key, since not an option
          "x-goog-encryption-key-sha256" => Digest::SHA256.base64digest(options[:key])
        } if options[:key]

        @client.execute api_method: @storage.objects.insert,
                        media: media,
                        parameters: params,
                        body_object: insert_file_request(options),
                        headers: headers         # TODO: conditionalize
```

Then I uploaded a file with a key, and reloaded it to see the response. As described, "the object's CRC32C checksum and MD5 hash" were no longer in the response. Downloading also failed, although I haven't yet inspected the reason.

```sh
irb(main):009:0> cipher = OpenSSL::Cipher.new('aes-256-cbc')
=> #<OpenSSL::Cipher:0x007fdc8a055370>
irb(main):010:0> cipher.encrypt
=> #<OpenSSL::Cipher:0x007fdc8a055370>
irb(main):011:0> key = cipher.random_key
=> "\xD5L\xFCA\xA2\x84mbA\xA95)T\xAA\x03\xAA\xEF\xD6\x9C\xBF\f\xDE\x97\x10\xDA\x00\x8Dd\xA3\xA6`s"
irb(main):012:0> file = bucket.create_file "./LICENSE", key: key
=> #<Gcloud::Storage::File:0x007fdc8b9d4800 @connection=Gcloud::Storage::Connection(bustling-kayak-91516), @gapi=#<Google::APIClient::Schema::Storage::V1::Object:0x3fee45cea478 DATA:{"kind"=>"storage#object", "id"=>"my-bucket123321/./LICENSE/1465254998004000", "selfLink"=>"https://www.googleapis.com/storage/v1/b/my-bucket123321/o/.%2FLICENSE", "name"=>"./LICENSE", "bucket"=>"my-bucket123321", "generation"=>"1465254998004000", "metageneration"=>"1", "timeCreated"=>"2016-06-06T23:16:37.982Z", "updated"=>"2016-06-06T23:16:37.982Z", "storageClass"=>"STANDARD", "size"=>"11357", "md5Hash"=>"htPzqVwyTJR5vYmGlo9DJw==", "mediaLink"=>"https://www.googleapis.com/download/storage/v1/b/my-bucket123321/o/.%2FLICENSE?generation=1465254998004000&alt=media", "crc32c"=>"Kqo3Ow==", "etag"=>"CKCipZ3ElM0CEAE=", "customerEncryption"=>{"encryptionAlgorithm"=>"AES256", "keySha256"=>"IrXFw/lSDiYNqaqQPXrHcCygAO8bRA49aBsfjQCiwxs="}}>>
irb(main):013:0> file.reload!
=> #<Google::APIClient::Schema::Storage::V1::Object:0x3fee4694ca68 DATA:{"kind"=>"storage#object", "id"=>"my-bucket123321/./LICENSE/1465254998004000", "selfLink"=>"https://www.googleapis.com/storage/v1/b/my-bucket123321/o/.%2FLICENSE", "name"=>"./LICENSE", "bucket"=>"my-bucket123321", "generation"=>"1465254998004000", "metageneration"=>"1", "timeCreated"=>"2016-06-06T23:16:37.982Z", "updated"=>"2016-06-06T23:16:37.982Z", "storageClass"=>"STANDARD", "size"=>"11357", "mediaLink"=>"https://www.googleapis.com/download/storage/v1/b/my-bucket123321/o/.%2FLICENSE?generation=1465254998004000&alt=media", "etag"=>"CKCipZ3ElM0CEAE=", "customerEncryption"=>{"encryptionAlgorithm"=>"AES256", "keySha256"=>"IrXFw/lSDiYNqaqQPXrHcCygAO8bRA49aBsfjQCiwxs="}}>
irb(main):014:0> file.download "./LICENSE-COPY"
NoMethodError: undefined method `[]' for nil:NilClass
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/storage/errors.rb:48:in `from_response'
	from /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/storage/file.rb:355:in `download'
	from (irb):14
```

**Comment by quartzmo** [comment]
If you scroll over far enough to the right, you can see that the response contains:

```js
"customerEncryption"=>{"encryptionAlgorithm"=>"AES256", "keySha256"=>"IrXFw/lSDiYNqaqQPXrHcCygAO8bRA49aBsfjQCiwxs="}
```

**Comment by blowmage** [comment]
Awesome. I can't wait to have some design discussions on how to expose this in the ruby API!

**Comment by quartzmo** [comment]
The response is `400`:

```sh
@response=#<Faraday::Response:0x007fe60b120ec8 ...> ... "content-length"=>"72", "server"=>"UploadServer", "alternate-protocol"=>"443:quic", "alt-svc"=>"quic=\":443\"; ma=2592000; v=\"34,33,32,31,30,29,28,27,26,25\"", "connection"=>"close"} @status=400>>
```

**Comment by blowmage** [comment]
Its a bug in the error handling then. Good catch!

**Comment by quartzmo** [comment]
I successfully completed a roundtrip insert, get, and download using a customer-supplied key (below). My [branch is here](https://github.com/quartzmo/gcloud-ruby/tree/storage-keys) if anyone wants to try it.

```sh
irb(main):002:0> bucket = storage.bucket "my-bucket123321"
=> #<Gcloud::Storage::Bucket:0x007f91031206d8 @connection=Gcloud::Storage::Connection(bustling-kayak-91516), @gapi=#<Google::APIClient::Schema::Storage::V1::Bucket:0x3fc881890574 DATA:{"kind"=>"storage#bucket", "id"=>"my-bucket123321", "selfLink"=>"https://www.googleapis.com/storage/v1/b/my-bucket123321", "projectNumber"=>"664476911263", "name"=>"my-bucket123321", "timeCreated"=>"2016-06-06T23:07:41.263Z", "updated"=>"2016-06-06T23:07:41.263Z", "metageneration"=>"1", "location"=>"US", "storageClass"=>"STANDARD", "etag"=>"CAE="}>>
irb(main):003:0> key = "\xD5L\xFCA\xA2\x84mbA\xA95)T\xAA\x03\xAA\xEF\xD6\x9C\xBF\f\xDE\x97\x10\xDA\x00\x8Dd\xA3\xA6`s"
=> "\xD5L\xFCA\xA2\x84mbA\xA95)T\xAA\u0003\xAA\xEF֜\xBF\fޗ\u0010\xDA\u0000\x8Dd\xA3\xA6`s"
irb(main):004:0> file = bucket.file "./LICENSE", key: key
=> #<Gcloud::Storage::File:0x007f9103053f48 @connection=Gcloud::Storage::Connection(bustling-kayak-91516), @gapi=#<Google::APIClient::Schema::Storage::V1::Object:0x3fc88182c0d8 DATA:{"kind"=>"storage#object", "id"=>"my-bucket123321/./LICENSE/1465254998004000", "selfLink"=>"https://www.googleapis.com/storage/v1/b/my-bucket123321/o/.%2FLICENSE", "name"=>"./LICENSE", "bucket"=>"my-bucket123321", "generation"=>"1465254998004000", "metageneration"=>"1", "timeCreated"=>"2016-06-06T23:16:37.982Z", "updated"=>"2016-06-06T23:16:37.982Z", "storageClass"=>"STANDARD", "size"=>"11357", "md5Hash"=>"htPzqVwyTJR5vYmGlo9DJw==", "mediaLink"=>"https://www.googleapis.com/download/storage/v1/b/my-bucket123321/o/.%2FLICENSE?generation=1465254998004000&alt=media", "crc32c"=>"Kqo3Ow==", "etag"=>"CKCipZ3ElM0CEAE=", "customerEncryption"=>{"encryptionAlgorithm"=>"AES256", "keySha256"=>"IrXFw/lSDiYNqaqQPXrHcCygAO8bRA49aBsfjQCiwxs="}}>>
irb(main):005:0> file.download "./LICENSE-COPY", key: key
=> #<File:./LICENSE-COPY>
```

**Comment by quartzmo** [comment]
Thanks @blowmage for helping me debug some of this, or I would still be at it... :)

**Comment by quartzmo** [comment]
@jgeewax We can definitely do this. How urgent should we consider it?

**Comment by blowmage** [comment]
I see three main options for specifying keys:

1) Globally
2) Per Session
3) Per API Call

Do we allow users to configure all 3?

**Comment by blowmage** [comment]
@quartzmo Which API calls support custom encryption keys?

**Comment by quartzmo** [comment]
@blowmage They are not listed, but implicitly it seems every operation on the stored object (File):

> You upload an object using a customer-supplied encryption key, and you attempt to perform another operation on the object (other than requesting or updating metadata) without providing the key.

-- [Managing Data Encryption](https://cloud.google.com/storage/docs/encryption#response)

**Comment by blowmage** [comment]
Does listing files in a bucket behave differently if a custom key is provided? Like, do you get or not get the md5 hash when listing files?

**Comment by quartzmo** [comment]
I haven't tried it, but I would guess that the md5 would be omitted. I will try it in a bit.

**Comment by jgeewax** [comment]
I think people will want to specify a key *per file* -- and not per session or per API call.

In the future, they will want to use some key derivation function that they set at the top level, but to start the focus is "when I upload a file, let me give you a key to encrypt it with". Does that make life any easier?

**Comment by quartzmo** [comment]
@jgeewax Maybe we can work incrementally toward such higher-level conveniences? Should we start just by adding key-per-API request support? That's not hard to do, my [spike branch](https://github.com/quartzmo/gcloud-ruby/tree/storage-keys) already adds it for a few methods.

**Comment by blowmage** [comment]
Makes sense. Thanks for clarifying the direction.

**Comment by quartzmo** [comment]
The key headers do not seem to be used in these API methods: 

* [Objects: list](https://cloud.google.com/storage/docs/json_api/v1/objects/list) - even if there is only one object in the bucket, passing the key used to insert it does not return a representation including `md5`, etc
* [Objects: delete](https://cloud.google.com/storage/docs/json_api/v1/objects/delete) - deleting an object is successful even without passing the key used to insert it
