### ISSUE TITLE
Error granting a View access to a Dataset

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#785]
I get this error while attempting to grant Dataset access to a View:

```ruby
dataset.access do |acl|
    acl.add_reader_view view # instance of View belonging to another Dataset
end
```

```sh
Gcloud::InvalidArgumentError: invalid: An access entry for view needs an empty role.
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/service.rb:90:in `rescue in patch_dataset'
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/service.rb:88:in `patch_dataset'
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/dataset.rb:683:in `patch_gapi!'
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/dataset.rb:264:in `access'
```

**Comment by blowmage** [comment]
So happy you found this. Yay acceptance tests!
